name: Production Apply

on:
  push:
    branches: [main]

jobs:
  plan:
    name: Terraform Plan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
      - uses: gruntwork-io/terragrunt-action@v2
        with:
          terragrunt_version: "0.55.0"
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - run: terragrunt run-all init --terragrunt-working-dir environments/prod
      - run: terragrunt run-all apply --terragrunt-working-dir environments/prod --terragrunt-non-interactive